[versions]

[libraries]
# Core dependencies
annotations = "org.jetbrains:annotations:26.0.1"
paper-api = "io.papermc.paper:paper-api:1.21.8-R0.1-SNAPSHOT"

# API dependencies
colorparser = "io.github.milkdrinkers:colorparser:3.0.1"
commandapi-shade = "dev.jorel:commandapi-bukkit-shade:10.1.2"

[bundles]

[plugins]
shadow = "com.gradleup.shadow:8.3.8"
run-paper = "xyz.jpenilla.run-paper:2.3.1"
plugin-yml = "de.eldoria.plugin-yml.bukkit:0.7.1"
